name: Soy johansitoweb

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say hello
        run: echo "Hello, johansitoweb!"
        
      - name: Display current date and time
        run: date